baseURL = 'https://patrek.github.io'
languageCode = 'en-ca'
title = "Patrek's blog"
description = "This is where I post my blog articles"
theme = 'ananke'

[params]
author = "patrek"
show_reading_time = true
date_format = "2006-01-02"
featured_image = "/images/gold.jpg"

[languages]
  [languages.en]
    disabled = false
    languageCode = ''
    languageDirection = ''
    languageName = ''
    contentDir = "content/en"
    title = "Patrek's blog"
    weight = 2
  [languages.fr]
    disabled = false
    languageCode = ''
    languageDirection = ''
    languageName = ''
    contentDir = "content/fr"
    title = "Blog de Patrek"
    weight = 1
  
  [params.ananke.social.share]
  networks = [
  "email",
  "facebook",
  "bluesky",
  "linkedin"
]

  [params.ananke.social.follow]
  networks = [
  "facebook",
  "bluesky",
  "linkedin"
]

  [ params.ananke.social.facebook ]
  username = "patrick.kollitsch"
  # profilelink = "https://www.facebook.com/patrick.kollitsch"

  [ params.ananke.social.linkedin ]
  username = "patrickkollitsch"

  [ params.ananke.social.bluesky ]
  username = "kollitsch.dev"

[security]
  enableInlineShortcodes = false

  [security.exec]
    allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^git$', '^npx$', '^postcss$', '^tailwindcss$', '^asciidoctor$']
    osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG|SYSTEMDRIVE)$']

  [security.funcs]
    getenv = ['^HUGO_', '^CI$']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']


