baseURL = 'https://patrek.github.io'
languageCode = 'en-ca'
title = "Patrek's blog"
description = "This is where I post my blog articles"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]
#theme = "silhouette-hugo"
#theme = ["github.com/razonyang/hugo-theme-bootstrap/v1.9"]
  
#staticDir = ["static", "themes/Niello/static"]
  
#theme = "Niello"

[params]
author = "Patrick Turcotte"
show_reading_time = true
date_format = "2006-01-02"
featured_image = "/images/gold.jpg"
custom_css = ["tables.css"]

[languages]
  [languages.en]
    disabled = false
    languageCode = ''
    languageDirection = ''
    languageName = ''
    contentDir = "content/en"
    title = "Patrek's blog"
    weight = 2
  [languages.fr]
    disabled = false
    languageCode = ''
    languageDirection = ''
    languageName = ''
    contentDir = "content/fr"
    title = "Blog de Patrek"
    weight = 1


[security]
  enableInlineShortcodes = false

  [security.exec]
    allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^git$', '^npx$', '^postcss$', '^tailwindcss$', '^asciidoctor$']
    osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG|SYSTEMDRIVE)$']

  [security.funcs]
    getenv = ['^HUGO_', '^CI$']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']


